title: Tyler Noble # your name (or website title) here
logo: "/images/alsome.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pragmatic and responsible engineering is a passion of mine that I bring to the table with every project I do. I'm a self starter who's fascination with software goes as far back as I can remember. 
  I'm also a big believer in the human side of engineering so anything from UX to internal team communication to customer support is all a part of the picture that I am constantly trying to improve. 
  I'm technology agnostic and am willing to learn anything that is needed to deliver the best product.
  <a href="/Resume/TylerNobleResume.pdf">See my resume</a>
  <br>
  <a href="mailto:tynobledev@gmail.com?Subject=Nice Portfolio" target="_top">Email me</a>
  <br>
  <a href="https://www.linkedin.com/in/nobletyler/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://www.twitter.com/_NobleTyler">Follow me on Twitter</a> 
  <br>
  <a href="https://calendly.com/tynobledev/networking">Book a call with me</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
